### ISSUE TITLE
Better css solution around the corner

### ISSUE THREAD

**Issue by ScriptedAlchemy** [teamable-software/css-chunks-html-webpack-plugin#7]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60

Might help

**Comment by mike1808** [comment]
@zackljackson what did you mean with "corner"?

**Comment by ScriptedAlchemy** [comment]
Hey! Pretty it’s almost ready, it’s installab under @next on npm. Check the thread and see if it’s of any use
